---
- hosts: all
  vars_files:
    - vars/main.yml
  handlers:
  - import_tasks: handlers/main.yml

  tasks:
    - name: configure dhcpd
      include_tasks:
        file: tasks/configure_dhcpd.yml
      tags:
        - configure_dhcpd
        - never

    - name: configure ocp zone on bind utils
      include_tasks:
        file: tasks/configure_bind_dns.yml
      tags:
        - configure_ocpzone_bindutils
        - never

    - name: configure tftp and syslinux
      include_tasks:
        file: tasks/configure_tftp_pxe.yml
      tags:
        - configure_tftp
        - never

    - name: configure HAProxy as load balancer on utility node
      include_tasks:
        file: tasks/configure_haproxy_lb.yml
      tags:
        - configure_lb 
        - never

    - name: install OCP installer and cli 
      include_tasks:
        file: tasks/install_ocp.yml
      tags:
        - install_ocp
        - never

    - name: Generate ignition files on utility 
      include_tasks:
        file: tasks/generate_ignition.yaml
      tags:
        - generate_ignition
        - never

    - name: Generate ignition files on utility 
      include_tasks:
        file: tasks/create_ocp_vms.yml
      tags:
        - create_vms_ocp
        - never


