---
- hosts: all
  vars_files:
    - vars/main.yml
  handlers:
  - import_tasks: handlers/main.yml

  tasks:
    - name: configure dhcpd
      include_tasks:
        file: tasks/configure_dhcpd.yml
      tags:
        - configure_dhcpd
