---
- hosts: all
  vars_files:
    - vars/main.yml
  handlers:
  - import_tasks: handlers/main.yml

  tasks:
    - name: configure dhcpd
      include_tasks:
        file: tasks/configure_dhcpd.yml
      tags:
        - configure_dhcpd
        - never

    - name: configure ocp zone on bind utils
      include_tasks:
        file: tasks/configure_bind_dns.yml
      tags:
        - configure_ocpzone_bindutils
        - never

    - name: configure tftp and syslinux
      include_tasks:
        file: tasks/configure_tftp_pxe.yml
      tags:
        - configure_tftp
        - never

    - name: configure HAProxy as load balancer on utility node
      include_tasks:
        file: tasks/configure_tftp_pxe.yml
      tags:
        - configure_lb 
        - never


