---
# Configure OCP4 HAProxy Load balancer on Helper Node

  - name: install haproxy
    yum:
      name:
        - haproxy
      state: present
    tags:
      - configure_lb
  - name: set SEBool to allow haproxy connect any port
    shell:
      cmd: setsebool -P haproxy_connect_any 1
    tags:
      - configure_lb

  - name: backup default HAProxy configuration
    shell:
      cmd: mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.default
    tags:
      - configure_lb

  - name: Write out haproxy config file
    template:
      src: ../templates/haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
    notify:
      - restart haproxy
    tags:
      - configure_lb

  - name: Configure SElinux for HAProxy to use the custom ports configured
    community.general.seport:
        ports: "{{ item }}"
        proto: tcp
        setype: http_port_t
        state: present
    loop:
      - 6443
      - 22623
      - 32700
    tags:
      - configure_lb

  - name: configure firewall
    shell:
      cmd: "{{ item }}"
    loop:
      - firewall-cmd --add-service={http,https} --permanent
      - firewall-cmd --add-port={6443,22623}/tcp --permanent
      - firewall-cmd --reload
    tags:
      - configure_lb


