---
# Configure OCP4 DNS Server on Helper Node

  - name: insall bind utils
    yum:
      name:
       - bind
       - bind-utils
    tags:
      - configure_ocpzone_bindutils

  - name: copy set-dns-serial.sh
    copy:
      src: ../files/set-dns-serial.sh
      dest: /usr/local/bin/set-dns-serial.sh
      mode: '755'
    become: yes
    become_user: root
    tags:
      - configure_ocpzone_bindutils

  - name: Setup named configuration files
    block:
    - name: Write out named file
      template:
        src: ../templates/named.conf.j2
        dest: /etc/named.conf
      notify:
        - restart bind

    - name: Set zone serial number
      shell: "/usr/local/bin/set-dns-serial.sh"
      register: dymanicserialnumber

    - name: Setting serial number as a fact
      set_fact:
        serialnumber: "{{ dymanicserialnumber.stdout }}"

    - name: Write out "{{ dns.domain | lower }}" zone file
      template:
        src: ../templates/zonefile.j2
        dest: /var/named/zonefile.db
        mode: '0644'
      notify:
        - restart bind

    - name: Write out reverse zone file
      template:
        src: ../templates/reverse.j2
        dest: /var/named/reverse.db
        mode: '0644'
      notify:
        - restart bind
    tags:
      - configure_ocpzone_bindutils

  - name: modify interface
    shell: 
      cmd: nmcli connection modify "{{ helper.networkifacename }}"  ipv4.dns "{{ helper.ipaddr }}"
    tags:
      - configure_ocpzone_bindutils

  - name: reloading connection
    shell: 
      cmd: nmcli connection reload
    tags:
      - configure_ocpzone_bindutils

  - name: opening firewall for services
    ansible.posix.firewalld:
      service: "{{ item }}"
      permanent: true
      state: enabled
    loop:
      - dhcp
      - tftp
      - http
      - https
      - dns
    tags:
      - configure_ocpzone_bindutils
  - name: restart firewalld
    shell:
      cmd: firewall-cmd --reload
    tags:
      - configure_ocpzone_bindutils



