---
- name: create bootstrap vm for ocp
  block:
  - name: get the template
    vars:
      vm_type: "bootstrap"
    template:
      src: ocp_vm_creator.j2.sh
      dest: ocp_vm_creator.sh

  - name: create the vm
    command: bash ocp_vm_creator.sh

  - name: wait for VM to spun
    pause:
       seconds: 150

  - name: start the vm
    community.libvirt.virt:
       name: "{{ bootstrap['name'].dns['clusterid'].dns['domain'] }}"
       state: running
  tags:
    - create_vms_ocp
    - never

- name: create master vm for ocp
  block:
  - name: get the template for master 1
    vars:
      vm_type: "master01"
    template:
      src: ocp_vm_creator.j2.sh
      dest: ocp_vm_creator_master01.sh

  - name: create the vm
    command: bash ocp_vm_creator_master01.sh

  - name: wait for VM to spun
    pause:
       seconds: 150

  - name: get the template for master 2
    vars:
      vm_type: "master02"
    template:
      src: ocp_vm_creator.j2.sh
      dest: ocp_vm_creator_master02.sh

  - name: create the vm
    command: bash ocp_vm_creator_master02.sh

  - name: wait for VM to spun
    pause:
       seconds: 150

  - name: get the template for master 3
    vars:
      vm_type: "master03"
    template:
      src: ocp_vm_creator.j2.sh
      dest: ocp_vm_creator_master03.sh

  - name: create the vm
    command: bash ocp_vm_creator_master03.sh

  - name: wait for VM to spun
    pause:
       seconds: 150

  tags:
    - create_vms_ocp
    - never

- name: start the master vms
  community.libvirt.virt:
     name: "{{ item['name'].dns['clusterid'].dns['domain'] }}"
     state: running
  loop: "{{ masters }}"


- name: create worker vm for ocp
  block:
  - name: get the template
    vars:
      vm_type: "worker01"
    template:
      src: ocp_vm_creator.j2.sh
      dest: ocp_vm_creator_worker01.sh

  - name: create the vm
    command: bash ocp_vm_creator_worker01.sh
  tags:
    - never



