---
- name: restart tftp
  service:
    name: tftp
    state: restarted
    #enabled: yes

- name: restart bind
  service:
    name: named
    state: restarted
    enabled: yes
  tags:
    - configure_ocpzone_bindutils

- name: restart haproxy
  service:
    name: haproxy
    state: restarted
    enabled: yes

- name: restart dhcpd
  service:
    name: dhcpd
    state: restarted
    enabled: yes
  tags:
    - configure_dhcpd

- name: restart tftp
  service:
    name: tftp
    state: restarted
    enabled: yes
  tags:
    - configure_tftp

- name: restart tftph
  service:
    name: helper-tftp
    state: restarted
    enabled: yes
  tags:
    - configure_tftp

- name: restart httpd
  service:
    name: httpd
    state: restarted
    enabled: yes
  tags:
    - configure_tftp

- name: restart libvirtd
  service:
    name: libvirtd
    state: restarted
    enabled: yes
  tags:
    - create_vms_ocp
