---
- name: restart tftp
  service:
    name: tftp
    state: restarted
    #enabled: yes

- name: restart bind
  service:
    name: named
    state: restarted
    enabled: yes
  tags:
    - configure_ocpzone_bindutils

- name: restart haproxy
  service:
    name: haproxy
    state: restarted
    enabled: yes

- name: restart httpd
  service:
    name: httpd
    state: restarted
    enabled: yes
  tags:
    - configure_dhcpd
