apiVersion: v1
baseDomain: example.com
compute:
- hyperthreading: Enabled
  name: worker
  replicas: 0
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 2
metadata:
  name: ocp4
networking:
  clusterNetworks:
  - cidr: 10.254.0.0/16
    hostPrefix: 24
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  none: {}
pullSecret: '$(< /root/.openshift/pull-secret)'
sshKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDOfnI+QPWIgO0CPTSy8EzPBQGwVAMCn3KgYbFtSXosOB/guGyDlzJcmFq1whOlgHqSDrOAfSMTvH7pFG6dT0dhgR3rWlWQMQLQwIJAAXlXTGLC2XKmwwyKsAI+6UBCGiuFjHIAaae2QPKSn9zspifcAoH1kHLCAg2v34ZGrY3GslTWjSZVxBrbqkfXtUeesUZwhh2P7Kqr+KTHWoYcbQbe9UVjuBHa3updLRvlmQ5uwlmZNeDiL8vlnq/YKGH5gn8OndGA6pHIUbieSqbiuv6bCbTNPFeyk3wA4JfXnmoYwHBlYnUbFnG1BV/FMXGiX7LyzPd0flL084aYhoCX+AtbXIB10v0VTKaXAlPaTQOjHSGXf2k0YBIDhKk3FQ4tMiKzU7iIiqmUzJqpjML0iCil66wDul8Gc5nHbev2hk+lY47X+GiPj9WB99AAKSNPqxAIAC+DD/oCB6l5Pr9LMKY2lirZ99VK7n8eLZfepTuYehms4K7Igal+MbTklM8EV/t+mP5Amj1LtSjtoLy0K3Rl8LbPUwRi5cMIJ9wt90MFedK3B+f+3jkgaObf22ic+Y0XSanTCVfQtCKQiG7C9RaAgJYHibew0q5IVgOVQxKo3yu5B/nSl5ZoOCJqRy4FIgpncm9VEn7qJYuan5Loou+LrdWq09uXt6a3vtr/aK3uVQ=='
